### ISSUE TITLE
No documentation on connecting to horizon

### ISSUE THREAD

**Issue by ravbahra** [rocky1109/pyVirtualize#1]
Hi
I've looked through the code but there doesn't seem to be any references to horizon view, the only reference I can see is in the features that pyVirtualize provides an easy interface to horizon view.

Any ideas on how to connect to the Horizon server? There doesn't seem to be any obvious way of doing so. Also...if there are any functions to get pools etc.

Thanks 
RB

**Comment by mizsum** [comment]
I am looking for any sample code to connect to Horizon View as well. Using this pyVirtualize or any other available python SDK to connect to View APIs. Please post some sample codes here

**Comment by ravbahra** [comment]
@mizsum - I ended up combining pyVirtualize with PowerCLI. I needed to use VMWare.Hv.Helper from here https://github.com/vmware/PowerCLI-Example-Scripts/tree/master/Modules/VMware.Hv.Helper. With that you should be able to automate pool creation.

There are some examples in there that will get you going.

**Comment by rocky1109** [comment]
Guys, SDKs for Horizon View had to be got down for confidential reasons. Sorry for any inconvenience caussed.

I have update the README respectively.
Further I may not help you with the code, but we can exchange an idea about how to do it.
Cheer, Rocky. (y)
