### ISSUE TITLE
Modify CPU value

### ISSUE THREAD

**Issue by Rockawear** [rocky1109/pyVirtualize#15]
Hi,

Thank you for creating this helpful package. How can I modify the cpu value 'numCpu'? Should I use it like any regular dictionary? will this change the number of CPU for the vm?

**Comment by rocky1109** [comment]
No it will not. There's no direct method available to perform vm settings modification.
Although you can leverage the vmomi object to set new configs as required, something like specified in this thread: https://github.com/vmware/pyvmomi-community-samples/issues/265
Further pyVirtualize's every VirtualMachine object provides access to respective vmomi object at: **VirtualMachine.vim.vmomi_object**
